import '../models/inventory_item.dart';

/// Demo inventory for a big-box hardware store: 100 products across 12
/// departments, each with an in-store aisle, shelf, and bin location.
/// Loaded on first launch and again by the demo "Upload Data" action.
const List<InventoryItem> inventorySeed = [
  InventoryItem(
    sku: '223948255',
    name: '2 in. x 4 in. x 8 ft. Premium Stud',
    brand: 'Lumber Co.',
    department: 'Lumber & Building Materials',
    price: 3.98,
    quantity: 88,
    aisle: 2,
    shelf: 5,
    bin: 'D4',
    description: 'Kiln-dried whitewood stud for framing.',
  ),
  InventoryItem(
    sku: '287619579',
    name: '2 in. x 6 in. x 10 ft. Pressure-Treated Lumber',
    brand: 'Lumber Co.',
    department: 'Lumber & Building Materials',
    price: 12.47,
    quantity: 0,
    aisle: 1,
    shelf: 5,
    bin: 'A3',
    description: 'Ground-contact rated for decks and outdoor framing.',
  ),
  InventoryItem(
    sku: '208893036',
    name: '1/2 in. x 4 ft. x 8 ft. Drywall Panel',
    brand: 'USG',
    department: 'Lumber & Building Materials',
    price: 15.98,
    quantity: 149,
    aisle: 3,
    shelf: 6,
    bin: 'D2',
    description: 'Standard gypsum wallboard for interior walls.',
  ),
  InventoryItem(
    sku: '236469162',
    name: '23/32 in. x 4 ft. x 8 ft. Plywood Sheathing',
    brand: 'Georgia-Pacific',
    department: 'Lumber & Building Materials',
    price: 42.88,
    quantity: 63,
    aisle: 3,
    shelf: 4,
    bin: 'E4',
    description: 'Tongue-and-groove subfloor panel.',
  ),
  InventoryItem(
    sku: '338805606',
    name: '80 lb. Fast-Setting Concrete Mix',
    brand: 'Quikrete',
    department: 'Lumber & Building Materials',
    price: 7.28,
    quantity: 76,
    aisle: 1,
    shelf: 5,
    bin: 'E2',
    description: 'Sets in 20-40 minutes; no mixing required for posts.',
  ),
  InventoryItem(
    sku: '300988854',
    name: '60 lb. Mortar Mix',
    brand: 'Quikrete',
    department: 'Lumber & Building Materials',
    price: 8.47,
    quantity: 162,
    aisle: 1,
    shelf: 1,
    bin: 'F3',
    description: 'Type N mortar for brick and block.',
  ),
  InventoryItem(
    sku: '180354676',
    name: '4 in. x 8 in. x 16 in. Concrete Block',
    brand: 'Oldcastle',
    department: 'Lumber & Building Materials',
    price: 2.18,
    quantity: 152,
    aisle: 3,
    shelf: 1,
    bin: 'D3',
    description: 'Standard CMU block for walls and foundations.',
  ),
  InventoryItem(
    sku: '283798054',
    name: 'R-13 Kraft Faced Insulation Roll',
    brand: 'Owens Corning',
    department: 'Lumber & Building Materials',
    price: 21.97,
    quantity: 126,
    aisle: 2,
    shelf: 5,
    bin: 'B4',
    description: 'Fiberglass insulation for 2x4 walls, 40 sq. ft.',
  ),
  InventoryItem(
    sku: '338939618',
    name: '1 in. x 4 in. x 8 ft. Primed MDF Trim Board',
    brand: 'Alexandria Moulding',
    department: 'Lumber & Building Materials',
    price: 9.37,
    quantity: 156,
    aisle: 3,
    shelf: 4,
    bin: 'E2',
    description: 'Pre-primed trim, ready to paint.',
  ),
  InventoryItem(
    sku: '345233081',
    name: '#8 x 2-1/2 in. Exterior Deck Screws (1 lb.)',
    brand: 'Grip-Rite',
    department: 'Fasteners & Hardware',
    price: 9.97,
    quantity: 159,
    aisle: 5,
    shelf: 2,
    bin: 'E1',
    description: 'Coated star-drive screws for pressure-treated lumber.',
  ),
  InventoryItem(
    sku: '359844829',
    name: '#9 x 3 in. Construction Screws (5 lb.)',
    brand: 'GRK Fasteners',
    department: 'Fasteners & Hardware',
    price: 44.98,
    quantity: 1,
    aisle: 5,
    shelf: 4,
    bin: 'E1',
    description: 'Structural screws; no pre-drilling required.',
  ),
  InventoryItem(
    sku: '177131838',
    name: '16d Common Nails (5 lb.)',
    brand: 'Grip-Rite',
    department: 'Fasteners & Hardware',
    price: 13.48,
    quantity: 128,
    aisle: 6,
    shelf: 1,
    bin: 'B1',
    description: 'Bright common nails for general framing.',
  ),
  InventoryItem(
    sku: '320296502',
    name: '1/4 in. x 3 in. Hex Lag Screws (25-Pack)',
    brand: 'Everbilt',
    department: 'Fasteners & Hardware',
    price: 11.28,
    quantity: 143,
    aisle: 6,
    shelf: 6,
    bin: 'D4',
    description: 'Zinc-plated lag screws for heavy-duty fastening.',
  ),
  InventoryItem(
    sku: '259507125',
    name: 'Drywall Anchor Kit with Screws (100-Piece)',
    brand: 'E-Z Ancor',
    department: 'Fasteners & Hardware',
    price: 12.97,
    quantity: 27,
    aisle: 4,
    shelf: 3,
    bin: 'F4',
    description: 'Self-drilling anchors, up to 75 lb.',
  ),
  InventoryItem(
    sku: '229972668',
    name: '3/8 in. Toggle Bolts (10-Pack)',
    brand: 'Toggler',
    department: 'Fasteners & Hardware',
    price: 8.98,
    quantity: 76,
    aisle: 6,
    shelf: 5,
    bin: 'E4',
    description: 'Hollow wall anchors for shelving and mounts.',
  ),
  InventoryItem(
    sku: '175879528',
    name: '3-1/2 in. Satin Nickel Door Hinges (3-Pack)',
    brand: 'Everbilt',
    department: 'Fasteners & Hardware',
    price: 14.97,
    quantity: 13,
    aisle: 4,
    shelf: 6,
    bin: 'D3',
    description: 'Residential door hinges with 5/8 in. radius corners.',
  ),
  InventoryItem(
    sku: '264979468',
    name: 'Single Cylinder Keyed Entry Deadbolt',
    brand: 'Kwikset',
    department: 'Fasteners & Hardware',
    price: 29.98,
    quantity: 147,
    aisle: 5,
    shelf: 5,
    bin: 'B1',
    description: 'SmartKey re-key technology, satin nickel.',
  ),
  InventoryItem(
    sku: '336751124',
    name: 'Galvanized Joist Hanger for 2x6',
    brand: 'Simpson Strong-Tie',
    department: 'Fasteners & Hardware',
    price: 1.48,
    quantity: 145,
    aisle: 4,
    shelf: 3,
    bin: 'C2',
    description: 'Code-approved face-mount hanger.',
  ),
  InventoryItem(
    sku: '293163431',
    name: '20V MAX Cordless Drill/Driver Kit',
    brand: 'DEWALT',
    department: 'Power Tools',
    price: 159.00,
    quantity: 57,
    aisle: 8,
    shelf: 6,
    bin: 'E3',
    description: '1/2 in. chuck, 2 batteries, charger and bag.',
  ),
  InventoryItem(
    sku: '357927711',
    name: '20V MAX XR Impact Driver (Tool Only)',
    brand: 'DEWALT',
    department: 'Power Tools',
    price: 169.00,
    quantity: 3,
    aisle: 8,
    shelf: 4,
    bin: 'A2',
    description: 'Brushless, 3-speed, 1/4 in. hex chuck.',
  ),
  InventoryItem(
    sku: '255142127',
    name: 'M18 Cordless 7-1/4 in. Circular Saw',
    brand: 'Milwaukee',
    department: 'Power Tools',
    price: 199.00,
    quantity: 97,
    aisle: 7,
    shelf: 5,
    bin: 'F3',
    description: 'Brushless, 5,800 RPM, electric brake.',
  ),
  InventoryItem(
    sku: '342847319',
    name: '15 Amp 10 in. Compound Miter Saw',
    brand: 'RYOBI',
    department: 'Power Tools',
    price: 229.00,
    quantity: 15,
    aisle: 7,
    shelf: 3,
    bin: 'D1',
    description: 'Laser guide, 0-45 degree bevel.',
  ),
  InventoryItem(
    sku: '289592691',
    name: '18V ONE+ Cordless Jig Saw',
    brand: 'RYOBI',
    department: 'Power Tools',
    price: 69.97,
    quantity: 125,
    aisle: 8,
    shelf: 6,
    bin: 'B2',
    description: 'Variable speed with tool-free blade change.',
  ),
  InventoryItem(
    sku: '387398600',
    name: '5 in. Random Orbit Sander',
    brand: 'Makita',
    department: 'Power Tools',
    price: 79.00,
    quantity: 126,
    aisle: 8,
    shelf: 3,
    bin: 'A2',
    description: '3 Amp motor with dust collection bag.',
  ),
  InventoryItem(
    sku: '176593529',
    name: 'M18 FUEL Hammer Drill Kit',
    brand: 'Milwaukee',
    department: 'Power Tools',
    price: 299.00,
    quantity: 135,
    aisle: 7,
    shelf: 2,
    bin: 'F3',
    description: '1,200 in.-lbs torque, two 5.0Ah batteries.',
  ),
  InventoryItem(
    sku: '285646505',
    name: '20V MAX 4-1/2 in. Angle Grinder',
    brand: 'DEWALT',
    department: 'Power Tools',
    price: 139.00,
    quantity: 10,
    aisle: 7,
    shelf: 5,
    bin: 'E3',
    description: 'Paddle switch, 8,000 RPM.',
  ),
  InventoryItem(
    sku: '395165912',
    name: '6 Gal. Pancake Air Compressor with Brad Nailer',
    brand: 'Porter-Cable',
    department: 'Power Tools',
    price: 199.00,
    quantity: 109,
    aisle: 7,
    shelf: 4,
    bin: 'D1',
    description: '150 PSI, oil-free, includes 18-gauge nailer.',
  ),
  InventoryItem(
    sku: '212963628',
    name: '16 oz. Fiberglass Claw Hammer',
    brand: 'Estwing',
    department: 'Hand Tools',
    price: 29.97,
    quantity: 77,
    aisle: 9,
    shelf: 3,
    bin: 'A1',
    description: 'Shock-reduction grip, forged steel head.',
  ),
  InventoryItem(
    sku: '304925675',
    name: '25 ft. Tape Measure',
    brand: 'Stanley',
    department: 'Hand Tools',
    price: 19.98,
    quantity: 48,
    aisle: 10,
    shelf: 2,
    bin: 'F1',
    description: 'FATMAX with 11 ft. standout.',
  ),
  InventoryItem(
    sku: '137402295',
    name: '24 in. Aluminum Level',
    brand: 'Empire',
    department: 'Hand Tools',
    price: 24.97,
    quantity: 143,
    aisle: 9,
    shelf: 3,
    bin: 'A2',
    description: 'Magnetic edge with three vials.',
  ),
  InventoryItem(
    sku: '198766929',
    name: '10-in-1 Screwdriver',
    brand: 'Klein Tools',
    department: 'Hand Tools',
    price: 17.97,
    quantity: 1,
    aisle: 10,
    shelf: 3,
    bin: 'C3',
    description: 'Interchangeable bits with cushion grip.',
  ),
  InventoryItem(
    sku: '227244652',
    name: 'Mechanics Tool Set (230-Piece)',
    brand: 'Craftsman',
    department: 'Hand Tools',
    price: 149.00,
    quantity: 175,
    aisle: 10,
    shelf: 4,
    bin: 'E3',
    description: 'SAE and metric sockets with 3 drawer case.',
  ),
  InventoryItem(
    sku: '163198065',
    name: 'Utility Knife with 5 Blades',
    brand: 'Milwaukee',
    department: 'Hand Tools',
    price: 12.97,
    quantity: 36,
    aisle: 9,
    shelf: 6,
    bin: 'A3',
    description: 'Fastback folding knife, one-handed blade change.',
  ),
  InventoryItem(
    sku: '157851383',
    name: '8 in. Adjustable Wrench',
    brand: 'Channellock',
    department: 'Hand Tools',
    price: 21.98,
    quantity: 129,
    aisle: 10,
    shelf: 5,
    bin: 'F2',
    description: 'Code Blue grip, wide jaw capacity.',
  ),
  InventoryItem(
    sku: '269377372',
    name: '10 in. Tongue and Groove Pliers',
    brand: 'Knipex',
    department: 'Hand Tools',
    price: 38.97,
    quantity: 24,
    aisle: 9,
    shelf: 2,
    bin: 'B4',
    description: 'Cobra push-button adjustment.',
  ),
  InventoryItem(
    sku: '378938549',
    name: 'Hacksaw with 12 in. Blade',
    brand: 'Lenox',
    department: 'Hand Tools',
    price: 23.97,
    quantity: 55,
    aisle: 9,
    shelf: 1,
    bin: 'F3',
    description: 'High-tension frame, 50 lb. blade tension.',
  ),
  InventoryItem(
    sku: '124216705',
    name: 'Speed Square 7 in. Aluminum',
    brand: 'Swanson',
    department: 'Hand Tools',
    price: 11.97,
    quantity: 94,
    aisle: 10,
    shelf: 5,
    bin: 'D4',
    description: 'Rafter square with degree markings.',
  ),
  InventoryItem(
    sku: '371348791',
    name: '250 ft. 12/2 Romex Indoor Wire',
    brand: 'Southwire',
    department: 'Electrical',
    price: 124.00,
    quantity: 67,
    aisle: 12,
    shelf: 4,
    bin: 'F2',
    description: 'Solid copper NM-B with ground, yellow jacket.',
  ),
  InventoryItem(
    sku: '270880866',
    name: '15 Amp Tamper-Resistant Duplex Outlet (10-Pack)',
    brand: 'Leviton',
    department: 'Electrical',
    price: 14.97,
    quantity: 103,
    aisle: 12,
    shelf: 2,
    bin: 'A1',
    description: 'White, residential grade.',
  ),
  InventoryItem(
    sku: '120222312',
    name: '20 Amp GFCI Outlet',
    brand: 'Leviton',
    department: 'Electrical',
    price: 21.97,
    quantity: 1,
    aisle: 12,
    shelf: 6,
    bin: 'E3',
    description: 'Self-test with LED indicator, white.',
  ),
  InventoryItem(
    sku: '178645365',
    name: 'Single-Pole Toggle Light Switch',
    brand: 'Eaton',
    department: 'Electrical',
    price: 1.28,
    quantity: 146,
    aisle: 12,
    shelf: 6,
    bin: 'D4',
    description: '15 Amp, 120V, ivory.',
  ),
  InventoryItem(
    sku: '163682820',
    name: 'Decora Smart Wi-Fi Dimmer Switch',
    brand: 'Leviton',
    department: 'Electrical',
    price: 44.97,
    quantity: 167,
    aisle: 12,
    shelf: 4,
    bin: 'F4',
    description: 'Works with Alexa and Google, no hub needed.',
  ),
  InventoryItem(
    sku: '170585466',
    name: '1-Gang Old Work PVC Electrical Box',
    brand: 'Carlon',
    department: 'Electrical',
    price: 2.47,
    quantity: 4,
    aisle: 11,
    shelf: 1,
    bin: 'B2',
    description: 'Remodel box, 14 cu. in.',
  ),
  InventoryItem(
    sku: '177736760',
    name: 'Non-Contact Voltage Tester',
    brand: 'Klein Tools',
    department: 'Electrical',
    price: 19.97,
    quantity: 123,
    aisle: 11,
    shelf: 3,
    bin: 'C1',
    description: 'Detects 12-1000V AC with visual alert.',
  ),
  InventoryItem(
    sku: '272788556',
    name: '50 ft. 12/3 Outdoor Extension Cord',
    brand: 'Southwire',
    department: 'Electrical',
    price: 49.97,
    quantity: 3,
    aisle: 11,
    shelf: 2,
    bin: 'D4',
    description: 'Heavy-duty with lighted end, 15 Amp.',
  ),
  InventoryItem(
    sku: '356318126',
    name: '20 Amp Single-Pole Circuit Breaker',
    brand: 'Square D',
    department: 'Electrical',
    price: 9.98,
    quantity: 56,
    aisle: 11,
    shelf: 6,
    bin: 'E2',
    description: 'Homeline plug-on breaker.',
  ),
  InventoryItem(
    sku: '110779249',
    name: '60W Equivalent A19 LED Light Bulb (8-Pack)',
    brand: 'Philips',
    department: 'Lighting & Ceiling Fans',
    price: 17.97,
    quantity: 53,
    aisle: 14,
    shelf: 1,
    bin: 'C2',
    description: 'Daylight 5000K, non-dimmable.',
  ),
  InventoryItem(
    sku: '113954229',
    name: '6 in. Integrated LED Recessed Light Trim (6-Pack)',
    brand: 'Commercial Electric',
    department: 'Lighting & Ceiling Fans',
    price: 59.97,
    quantity: 160,
    aisle: 13,
    shelf: 3,
    bin: 'F3',
    description: 'Selectable color temperature, no can needed.',
  ),
  InventoryItem(
    sku: '262944631',
    name: '52 in. Indoor LED Ceiling Fan with Remote',
    brand: 'Hunter',
    department: 'Lighting & Ceiling Fans',
    price: 169.00,
    quantity: 104,
    aisle: 13,
    shelf: 3,
    bin: 'B2',
    description: 'Matte black, reversible motor.',
  ),
  InventoryItem(
    sku: '106968435',
    name: '4 ft. LED Shop Light',
    brand: 'Lithonia Lighting',
    department: 'Lighting & Ceiling Fans',
    price: 34.97,
    quantity: 0,
    aisle: 13,
    shelf: 3,
    bin: 'B4',
    description: '4000 lumens, linkable, plug-in.',
  ),
  InventoryItem(
    sku: '108959010',
    name: 'Motion-Activated Outdoor LED Security Light',
    brand: 'Defiant',
    department: 'Lighting & Ceiling Fans',
    price: 49.97,
    quantity: 104,
    aisle: 13,
    shelf: 5,
    bin: 'E3',
    description: 'Dual head, 180 degree sensor.',
  ),
  InventoryItem(
    sku: '368173843',
    name: 'Solar LED Pathway Lights (6-Pack)',
    brand: 'Hampton Bay',
    department: 'Lighting & Ceiling Fans',
    price: 39.97,
    quantity: 8,
    aisle: 13,
    shelf: 4,
    bin: 'E2',
    description: 'Stainless steel, auto dusk-to-dawn.',
  ),
  InventoryItem(
    sku: '205219520',
    name: 'Vanity Light Bar 3-Light Brushed Nickel',
    brand: 'Progress Lighting',
    department: 'Lighting & Ceiling Fans',
    price: 89.00,
    quantity: 160,
    aisle: 13,
    shelf: 6,
    bin: 'A4',
    description: 'Etched glass shades, damp rated.',
  ),
  InventoryItem(
    sku: '268149885',
    name: '1/2 in. x 10 ft. Copper Pipe Type M',
    brand: 'Mueller',
    department: 'Plumbing',
    price: 24.98,
    quantity: 45,
    aisle: 16,
    shelf: 3,
    bin: 'B3',
    description: 'Rigid copper tubing for water supply lines.',
  ),
  InventoryItem(
    sku: '289236247',
    name: '1/2 in. x 10 ft. PEX-A Tubing Red',
    brand: 'Uponor',
    department: 'Plumbing',
    price: 11.97,
    quantity: 156,
    aisle: 16,
    shelf: 6,
    bin: 'B1',
    description: 'Flexible hot water supply tubing.',
  ),
  InventoryItem(
    sku: '103227575',
    name: '1/2 in. SharkBite Push-to-Connect Coupling',
    brand: 'SharkBite',
    department: 'Plumbing',
    price: 8.97,
    quantity: 53,
    aisle: 17,
    shelf: 5,
    bin: 'F1',
    description: 'No soldering, works with PEX, copper, CPVC.',
  ),
  InventoryItem(
    sku: '309788538',
    name: '3 in. x 10 ft. PVC DWV Pipe',
    brand: 'Charlotte Pipe',
    department: 'Plumbing',
    price: 21.47,
    quantity: 9,
    aisle: 15,
    shelf: 5,
    bin: 'F4',
    description: 'Schedule 40 drain, waste and vent pipe.',
  ),
  InventoryItem(
    sku: '199963375',
    name: 'PVC Cement and Primer Combo Pack',
    brand: 'Oatey',
    department: 'Plumbing',
    price: 12.98,
    quantity: 161,
    aisle: 15,
    shelf: 4,
    bin: 'D1',
    description: '8 oz. purple primer and clear cement.',
  ),
  InventoryItem(
    sku: '229768109',
    name: 'Universal Toilet Fill Valve',
    brand: 'Fluidmaster',
    department: 'Plumbing',
    price: 10.97,
    quantity: 120,
    aisle: 16,
    shelf: 3,
    bin: 'D2',
    description: 'Adjustable 9-14 in., anti-siphon.',
  ),
  InventoryItem(
    sku: '225376034',
    name: '2-Handle Kitchen Faucet with Side Sprayer',
    brand: 'Glacier Bay',
    department: 'Plumbing',
    price: 69.00,
    quantity: 119,
    aisle: 16,
    shelf: 5,
    bin: 'F1',
    description: 'Chrome finish, ceramic disc cartridge.',
  ),
  InventoryItem(
    sku: '252642461',
    name: '40 Gal. Electric Water Heater',
    brand: 'Rheem',
    department: 'Plumbing',
    price: 549.00,
    quantity: 175,
    aisle: 16,
    shelf: 6,
    bin: 'B3',
    description: '6-year tank warranty, 4500W elements.',
  ),
  InventoryItem(
    sku: '354186166',
    name: '1/3 HP Garbage Disposal',
    brand: 'InSinkErator',
    department: 'Plumbing',
    price: 99.97,
    quantity: 108,
    aisle: 15,
    shelf: 3,
    bin: 'E1',
    description: 'Continuous feed with power cord included.',
  ),
  InventoryItem(
    sku: '100738515',
    name: 'Drain Auger 25 ft.',
    brand: 'RIDGID',
    department: 'Plumbing',
    price: 44.97,
    quantity: 134,
    aisle: 16,
    shelf: 4,
    bin: 'F2',
    description: 'Manual drum auger for sinks and tubs.',
  ),
  InventoryItem(
    sku: '211966607',
    name: '1 Gal. Eggshell Interior Paint and Primer, Ultra Pure White',
    brand: 'BEHR',
    department: 'Paint',
    price: 38.98,
    quantity: 169,
    aisle: 19,
    shelf: 1,
    bin: 'C2',
    description: 'One-coat hide, scrub resistant.',
  ),
  InventoryItem(
    sku: '147115629',
    name: '5 Gal. Flat Exterior Paint',
    brand: 'BEHR',
    department: 'Paint',
    price: 169.00,
    quantity: 125,
    aisle: 18,
    shelf: 2,
    bin: 'E3',
    description: 'Weather and fade resistant, tintable base.',
  ),
  InventoryItem(
    sku: '223925147',
    name: '1 Gal. Semi-Gloss Trim and Door Paint',
    brand: 'Glidden',
    department: 'Paint',
    price: 32.97,
    quantity: 0,
    aisle: 19,
    shelf: 2,
    bin: 'F2',
    description: 'Durable finish for trim, doors and cabinets.',
  ),
  InventoryItem(
    sku: '373419930',
    name: '1 Gal. Solid Color Deck Stain',
    brand: 'Thompson\'s WaterSeal',
    department: 'Paint',
    price: 36.98,
    quantity: 166,
    aisle: 20,
    shelf: 3,
    bin: 'A2',
    description: 'Waterproofing stain, tintable.',
  ),
  InventoryItem(
    sku: '138783490',
    name: 'Paint Roller Kit 9 in. (6-Piece)',
    brand: 'Wooster',
    department: 'Paint',
    price: 17.97,
    quantity: 0,
    aisle: 20,
    shelf: 1,
    bin: 'D3',
    description: 'Frame, tray, 2 covers and 2 brushes.',
  ),
  InventoryItem(
    sku: '218430799',
    name: '2 in. Angled Sash Paint Brush',
    brand: 'Purdy',
    department: 'Paint',
    price: 14.97,
    quantity: 34,
    aisle: 20,
    shelf: 2,
    bin: 'F4',
    description: 'Nylon/polyester blend for all paints.',
  ),
  InventoryItem(
    sku: '346175710',
    name: '1.88 in. x 60 yd. Painter\'s Tape',
    brand: 'ScotchBlue',
    department: 'Paint',
    price: 7.98,
    quantity: 42,
    aisle: 19,
    shelf: 3,
    bin: 'E3',
    description: 'Clean removal up to 14 days.',
  ),
  InventoryItem(
    sku: '208694150',
    name: '9 ft. x 12 ft. Canvas Drop Cloth',
    brand: 'Trimaco',
    department: 'Paint',
    price: 22.97,
    quantity: 112,
    aisle: 19,
    shelf: 2,
    bin: 'F1',
    description: 'Heavy-duty, reusable, leak resistant.',
  ),
  InventoryItem(
    sku: '344909630',
    name: '12 oz. Flat Black Spray Paint',
    brand: 'Rust-Oleum',
    department: 'Paint',
    price: 5.98,
    quantity: 92,
    aisle: 19,
    shelf: 6,
    bin: 'D4',
    description: 'Painter\'s Touch 2X coverage.',
  ),
  InventoryItem(
    sku: '373397110',
    name: '32 oz. Lightweight Spackling',
    brand: 'DAP',
    department: 'Paint',
    price: 8.97,
    quantity: 109,
    aisle: 18,
    shelf: 1,
    bin: 'B1',
    description: 'Fills holes and cracks, paintable in 30 minutes.',
  ),
  InventoryItem(
    sku: '125303944',
    name: 'Luxury Vinyl Plank Flooring, Oak (23.6 sq. ft./case)',
    brand: 'LifeProof',
    department: 'Flooring',
    price: 69.44,
    quantity: 151,
    aisle: 21,
    shelf: 4,
    bin: 'B4',
    description: '100% waterproof click-lock plank.',
  ),
  InventoryItem(
    sku: '301416717',
    name: '12 in. x 24 in. Porcelain Floor Tile (13.3 sq. ft./case)',
    brand: 'MSI',
    department: 'Flooring',
    price: 26.47,
    quantity: 121,
    aisle: 21,
    shelf: 4,
    bin: 'C1',
    description: 'Matte gray, rated for floors and walls.',
  ),
  InventoryItem(
    sku: '175527659',
    name: 'Laminate Flooring Underlayment 100 sq. ft.',
    brand: 'QuietWalk',
    department: 'Flooring',
    price: 44.98,
    quantity: 70,
    aisle: 21,
    shelf: 3,
    bin: 'E4',
    description: 'Moisture barrier with sound reduction.',
  ),
  InventoryItem(
    sku: '334137898',
    name: '50 lb. Polymer-Modified Thinset Mortar',
    brand: 'Custom Building Products',
    department: 'Flooring',
    price: 24.98,
    quantity: 56,
    aisle: 21,
    shelf: 3,
    bin: 'D3',
    description: 'For porcelain and ceramic tile.',
  ),
  InventoryItem(
    sku: '112482682',
    name: 'Tile Spacers 1/8 in. (500-Pack)',
    brand: 'QEP',
    department: 'Flooring',
    price: 5.47,
    quantity: 168,
    aisle: 21,
    shelf: 6,
    bin: 'B4',
    description: 'Reusable plastic cross spacers.',
  ),
  InventoryItem(
    sku: '284620823',
    name: '2 cu. ft. Organic Potting Mix',
    brand: 'Miracle-Gro',
    department: 'Garden Center',
    price: 12.97,
    quantity: 3,
    aisle: 23,
    shelf: 6,
    bin: 'F2',
    description: 'Feeds plants up to 6 months.',
  ),
  InventoryItem(
    sku: '361715881',
    name: '2 cu. ft. Brown Mulch',
    brand: 'Vigoro',
    department: 'Garden Center',
    price: 3.97,
    quantity: 1,
    aisle: 23,
    shelf: 4,
    bin: 'C4',
    description: 'Shredded wood mulch, color-enhanced.',
  ),
  InventoryItem(
    sku: '363467468',
    name: '5,000 sq. ft. Lawn Fertilizer',
    brand: 'Scotts',
    department: 'Garden Center',
    price: 29.97,
    quantity: 15,
    aisle: 23,
    shelf: 6,
    bin: 'D3',
    description: 'Turf Builder with 32-0-4 formula.',
  ),
  InventoryItem(
    sku: '303749076',
    name: '100 ft. Garden Hose 5/8 in.',
    brand: 'Flexzilla',
    department: 'Garden Center',
    price: 69.97,
    quantity: 88,
    aisle: 22,
    shelf: 2,
    bin: 'C2',
    description: 'Kink resistant, lightweight hybrid polymer.',
  ),
  InventoryItem(
    sku: '285926831',
    name: 'Pistol Grip Hose Nozzle',
    brand: 'Gilmour',
    department: 'Garden Center',
    price: 9.97,
    quantity: 137,
    aisle: 23,
    shelf: 4,
    bin: 'B2',
    description: 'Adjustable spray, insulated grip.',
  ),
  InventoryItem(
    sku: '272238615',
    name: '21 in. Gas Push Lawn Mower',
    brand: 'Honda',
    department: 'Garden Center',
    price: 449.00,
    quantity: 71,
    aisle: 24,
    shelf: 2,
    bin: 'F2',
    description: '3-in-1 mulch, bag and discharge.',
  ),
  InventoryItem(
    sku: '379973655',
    name: '40V Cordless String Trimmer',
    brand: 'EGO',
    department: 'Garden Center',
    price: 199.00,
    quantity: 177,
    aisle: 24,
    shelf: 2,
    bin: 'C2',
    description: 'Brushless, 15 in. cutting swath, battery included.',
  ),
  InventoryItem(
    sku: '394948095',
    name: 'Round Point Digging Shovel',
    brand: 'Fiskars',
    department: 'Garden Center',
    price: 34.97,
    quantity: 3,
    aisle: 23,
    shelf: 6,
    bin: 'B2',
    description: 'Steel shaft, 48 in. handle.',
  ),
  InventoryItem(
    sku: '130974417',
    name: 'Bypass Pruning Shears',
    brand: 'Corona',
    department: 'Garden Center',
    price: 19.97,
    quantity: 1,
    aisle: 24,
    shelf: 5,
    bin: 'E1',
    description: 'Cuts up to 1 in. diameter.',
  ),
  InventoryItem(
    sku: '235186371',
    name: '6 cu. ft. Steel Wheelbarrow',
    brand: 'True Temper',
    department: 'Garden Center',
    price: 119.00,
    quantity: 24,
    aisle: 24,
    shelf: 6,
    bin: 'B1',
    description: 'Pneumatic tire, hardwood handles.',
  ),
  InventoryItem(
    sku: '163461418',
    name: '27 Gal. Tough Storage Tote with Lid',
    brand: 'HDX',
    department: 'Storage & Organization',
    price: 11.98,
    quantity: 180,
    aisle: 25,
    shelf: 6,
    bin: 'B2',
    description: 'Stackable, black with yellow lid.',
  ),
  InventoryItem(
    sku: '311723242',
    name: '5-Tier Steel Garage Shelving Unit',
    brand: 'Edsal',
    department: 'Storage & Organization',
    price: 89.97,
    quantity: 130,
    aisle: 25,
    shelf: 1,
    bin: 'A1',
    description: 'Holds up to 4,000 lb. total.',
  ),
  InventoryItem(
    sku: '170601157',
    name: '46 in. 9-Drawer Rolling Tool Chest',
    brand: 'Husky',
    department: 'Storage & Organization',
    price: 399.00,
    quantity: 134,
    aisle: 25,
    shelf: 2,
    bin: 'B4',
    description: 'Soft-close drawers with power strip.',
  ),
  InventoryItem(
    sku: '169429249',
    name: 'Wall-Mounted Pegboard 4 ft. x 2 ft.',
    brand: 'Wall Control',
    department: 'Storage & Organization',
    price: 44.97,
    quantity: 177,
    aisle: 25,
    shelf: 2,
    bin: 'E1',
    description: 'Steel pegboard with hooks included.',
  ),
  InventoryItem(
    sku: '330795932',
    name: 'Heavy-Duty Bike Storage Hook (2-Pack)',
    brand: 'Everbilt',
    department: 'Storage & Organization',
    price: 7.98,
    quantity: 39,
    aisle: 25,
    shelf: 4,
    bin: 'F2',
    description: 'Vinyl-coated, holds 50 lb. each.',
  ),
  InventoryItem(
    sku: '321902526',
    name: 'N95 Respirator Masks (20-Pack)',
    brand: '3M',
    department: 'Safety & Cleaning',
    price: 29.98,
    quantity: 140,
    aisle: 26,
    shelf: 2,
    bin: 'B4',
    description: 'NIOSH approved for dust and particles.',
  ),
  InventoryItem(
    sku: '135236279',
    name: 'Anti-Fog Safety Glasses',
    brand: 'DEWALT',
    department: 'Safety & Cleaning',
    price: 8.97,
    quantity: 40,
    aisle: 26,
    shelf: 3,
    bin: 'E2',
    description: 'Clear lens, ANSI Z87.1 rated.',
  ),
  InventoryItem(
    sku: '300308785',
    name: 'Hi-Vis Work Gloves Large (3-Pack)',
    brand: 'FIRM GRIP',
    department: 'Safety & Cleaning',
    price: 19.97,
    quantity: 0,
    aisle: 26,
    shelf: 2,
    bin: 'B3',
    description: 'Nitrile dipped for grip.',
  ),
  InventoryItem(
    sku: '216602006',
    name: 'Smoke and Carbon Monoxide Detector',
    brand: 'First Alert',
    department: 'Safety & Cleaning',
    price: 49.97,
    quantity: 106,
    aisle: 26,
    shelf: 6,
    bin: 'B2',
    description: 'Battery-operated combination alarm.',
  ),
  InventoryItem(
    sku: '249392263',
    name: '12 Gal. Wet/Dry Shop Vacuum',
    brand: 'RIDGID',
    department: 'Safety & Cleaning',
    price: 119.00,
    quantity: 0,
    aisle: 26,
    shelf: 3,
    bin: 'E1',
    description: '5.0 peak HP with blower port.',
  ),
  InventoryItem(
    sku: '259324394',
    name: 'Pro Grade Contractor Trash Bags 42 Gal. (32-Count)',
    brand: 'HDX',
    department: 'Safety & Cleaning',
    price: 24.97,
    quantity: 113,
    aisle: 26,
    shelf: 6,
    bin: 'B4',
    description: '3 mil thickness, flap tie.',
  ),
  InventoryItem(
    sku: '259166302',
    name: 'Fire Extinguisher Rechargeable',
    brand: 'Kidde',
    department: 'Safety & Cleaning',
    price: 39.97,
    quantity: 173,
    aisle: 26,
    shelf: 2,
    bin: 'F3',
    description: '1-A:10-B:C rated for home use.',
  ),
];
