/// A custom face generated by the user, or a built-in brand face
class CustomFace {
  final String id;
  final String description;

  /// File path on device for generated faces; asset path for built-ins.
  final String localPath;
  final DateTime createdAt;

  /// Built-in faces ship with the app as assets. They can't be deleted and are
  /// shown as a centered logo rather than a full-screen face.
  final bool isBuiltIn;

  const CustomFace({
    required this.id,
    required this.description,
    required this.localPath,
    required this.createdAt,
    this.isBuiltIn = false,
  });

  static final List<CustomFace> builtInFaces = [
    CustomFace(
      id: 'builtin_home_depot',
      description: 'The Home Depot',
      localPath: 'assets/icon/home_depot.png',
      createdAt: DateTime(2026),
      isBuiltIn: true,
    ),
  ];

  static CustomFace? builtInById(String? id) {
    if (id == null) return null;
    for (final face in builtInFaces) {
      if (face.id == id) return face;
    }
    return null;
  }

  factory CustomFace.fromJson(Map<String, dynamic> json) {
    return CustomFace(
      id: json['id'] as String,
      description: json['description'] as String,
      localPath: json['localPath'] as String,
      createdAt: DateTime.parse(json['createdAt'] as String),
    );
  }

  Map<String, dynamic> toJson() {
    return {
      'id': id,
      'description': description,
      'localPath': localPath,
      'createdAt': createdAt.toIso8601String(),
    };
  }
}
